name: Node.js CI

on:
  push:
    branches: [main, react-integration]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Change to frontend directory
        working-directory: ./bugs-frontend
        run: echo "Switched to bugs-frontend"

      - name: Delete existing npm cache
        run: npm cache clean --force

      - name: Clean install (no cache)
        working-directory: ./bugs-frontend
        run: npm ci

      - name: Debug Axios version
        working-directory: ./bugs-frontend
        run: npm ls axios

      - name: Lint code
        working-directory: ./bugs-frontend
        run: npm run lint

      - name: Run tests
        working-directory: ./bugs-frontend
        run: npm test

      - name: Format check
        working-directory: ./bugs-frontend
        run: npx prettier --check "src/**/*.{js,jsx,json,css}"

      - name: Build project
        working-directory: ./bugs-frontend
        run: npm run build
